const mongoose = require('mongoose');

const releaseSchema = new mongoose.Schema({
  project: { type: mongoose.Schema.Types.ObjectId, ref: 'Project', required: true },
  version: { type: String, required: true },
  title: { type: String, default: '' },
  changeRequests: [{ type: mongoose.Schema.Types.ObjectId, ref: 'ChangeRequest' }],
  status: {
    type: String,
    enum: ['Draft', 'Pending Approval', 'Approved', 'Released', 'Cancelled'],
    default: 'Draft',
  },
  releaseNotes: { type: String, default: '' },
  notesAutoGenerated: { type: Boolean, default: false },
  approvedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  approvedAt: { type: Date },
  releasedAt: { type: Date },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
}, { timestamps: true });

releaseSchema.index({ project: 1, version: 1 }, { unique: true });

module.exports = mongoose.model('Release', releaseSchema);
