const Release = require('../models/Release');
const ChangeRequest = require('../models/ChangeRequest');
const notificationService = require('../services/notificationService');

exports.list = async (req, res) => {
  try {
    const filter = {};
    if (req.query.project) filter.project = req.query.project;
    const releases = await Release.find(filter)
      .populate('project', 'name')
      .populate('changeRequests', 'title status riskScore')
      .populate('createdBy', 'name')
      .populate('approvedBy', 'name')
      .sort({ createdAt: -1 });
    res.json(releases);
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
};

exports.getById = async (req, res) => {
  try {
    const rel = await Release.findById(req.params.id)
      .populate('project', 'name')
      .populate('changeRequests', 'title status description riskScore')
      .populate('createdBy', 'name')
      .populate('approvedBy', 'name');
    if (!rel) return res.status(404).json({ error: 'Release not found' });
    res.json(rel);
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
};

exports.create = async (req, res) => {
  try {
    const { project, version, title, changeRequestIds } = req.body;
    if (!project) {
      return res.status(400).json({ error: 'Project is required' });
    }
    const rel = new Release({
      project,
      version,
      title: title || `Release ${version}`,
      changeRequests: changeRequestIds || [],
      status: 'Draft',
      createdBy: req.user._id,
    });
    await rel.save();
    if (changeRequestIds?.length) {
      await ChangeRequest.updateMany(
        { _id: { $in: changeRequestIds } },
        { $set: { linkedRelease: rel._id } }
      );
    }
    res.status(201).json(rel);
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
};

exports.updateCRs = async (req, res) => {
  try {
    const { changeRequestIds } = req.body;
    const rel = await Release.findById(req.params.id);
    if (!rel) return res.status(404).json({ error: 'Release not found' });
    rel.changeRequests = changeRequestIds || [];
    await rel.save();
    await ChangeRequest.updateMany({ linkedRelease: rel._id }, { $unset: { linkedRelease: 1 } });
    if (changeRequestIds?.length) {
      await ChangeRequest.updateMany(
        { _id: { $in: changeRequestIds } },
        { $set: { linkedRelease: rel._id } }
      );
    }
    res.json(rel);
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
};

exports.generateReleaseNotes = async (req, res) => {
  try {
    const rel = await Release.findById(req.params.id).populate('changeRequests', 'title changeType description');
    if (!rel) return res.status(404).json({ error: 'Release not found' });
    const lines = [`# ${rel.title || rel.version}`, '', '## Included change requests', ''];
    (rel.changeRequests || []).forEach((cr) => {
      lines.push(`- **${cr.title}** (${cr.changeType || 'Change'})`);
      if (cr.description) lines.push(`  - ${String(cr.description).slice(0, 200)}${cr.description.length > 200 ? '…' : ''}`);
    });
    rel.releaseNotes = lines.join('\n');
    rel.notesAutoGenerated = true;
    await rel.save();
    res.json(rel);
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
};

exports.submitForApproval = async (req, res) => {
  try {
    const rel = await Release.findById(req.params.id).populate('project', 'name');
    if (!rel) return res.status(404).json({ error: 'Release not found' });
    rel.status = 'Pending Approval';
    await rel.save();
    await notificationService.notifyAuditStakeholders(
      rel.project._id,
      `Release ${rel.version} pending approval for project ${rel.project.name}`,
      'RELEASE_PENDING_APPROVAL',
      rel._id
    );
    res.json(rel);
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
};

exports.approve = async (req, res) => {
  try {
    const rel = await Release.findById(req.params.id);
    if (!rel) return res.status(404).json({ error: 'Release not found' });
    rel.status = 'Approved';
    rel.approvedBy = req.user._id;
    rel.approvedAt = new Date();
    await rel.save();
    await notificationService.notifyProjectStakeholders(
      rel.project,
      `Release ${rel.version} approved`,
      'RELEASE_APPROVED',
      rel._id
    );
    res.json(rel);
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
};

exports.markReleased = async (req, res) => {
  try {
    const rel = await Release.findById(req.params.id);
    if (!rel) return res.status(404).json({ error: 'Release not found' });
    rel.status = 'Released';
    rel.releasedAt = new Date();
    await rel.save();
    res.json(rel);
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
};
